#!/bin/sh
#
# MOTD banner, shown when user connects via 'vagrant ssh'.
# This file is managed by Puppet.
#

rainbow_pipe () {
  local i=0 c
  while IFS= read data; do
    c=$(( 31 + ($i % 7) ))
    IFS=";" printf "\033[%sm" $c 1
    printf "%s\033[0m\n" "${data}"
    i=$((i+1))
  done
}
rainbow_pipe <<'EOM'
DOPA - VM 
EOM
echo
printf " * The files are located at \033[33;1m/dopa-vm/\033[0m.\n"
printf " * For help, visit \033[34;4mhttps://www.dopa-project.eu\033[0m or \033[33m#dima\033[0m on chat.freenode.net.\n\n"
/usr/bin/landscape-sysinfo --exclude-sysinfo-plugins=LandscapeLink
